# Generated by Django 5.1.7 on 2025-07-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_telephone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name_plural': 'Cours'},
        ),
    ]
